attributes:
  item_class:
    label: 'Item class'
    description: 'Add a class for menu item'
  link_class:
    label: 'Link class'
    description: 'Add a class for menu link'
  style:
    label: Style
    description: 'Add style attribute for menu item'
_core:
  default_config_hash: orvhFvLAM6e2N0f3GMUKFgQgE6meUEvwDb6Q1fUy5cU
