site_key: 6Lch8XcUAAAAAOxX-Xf79P2vpu1xTCUEOHjfwnVI
secret_key: 6Lch8XcUAAAAAAA7hjEoJt4LJ4Agfl74KlDpsRS3
widget:
  theme: light
  type: image
  size: ''
  tabindex: 0
  noscript: false
_core:
  default_config_hash: ZKQ03ePk4sH2zESRw4tdZYw__nG2YN4Ru5roPL23g3A
