site_key: 6LeJ6XcUAAAAAHUNQMc9WNa-qWH8ajYrndwLhw8z
secret_key: 6LeJ6XcUAAAAAF0Q4CtR33Gu5n1EoKdIlRqrksEo
widget:
  theme: light
  type: image
  size: ''
  tabindex: 0
  noscript: false
_core:
  default_config_hash: ZKQ03ePk4sH2zESRw4tdZYw__nG2YN4Ru5roPL23g3A
