add_item_msg: true
add_item_redirect: cart
msg_order_logged_in: ''
msg_order_existing_user: ''
msg_order_new_user: ''
msg_order_new_user_logged_in: ''
empty_button: false
minimum_subtotal: 0
anon_duration: 4
anon_unit: hours
auth_duration: 1
auth_unit: years
continue_shopping_type: button
continue_shopping_use_last_url: true
continue_shopping_url: /node/225
breadcrumb_text: ''
breadcrumb_url: ''
new_customer_login: false
new_customer_email: true
new_customer_status_active: true
new_account_name: false
new_account_password: false
checkout_email_customer: true
checkout_email_admin: true
mail_existing: true
email_validation: false
checkout_anonymous: true
checkout_enabled: true
panes:
  cart:
    status: true
    weight: 1
    id: cart
  customer:
    status: true
    weight: 2
    id: customer
  delivery:
    status: true
    weight: 3
    id: delivery
    settings:
      delivery_not_shippable: true
  billing:
    status: true
    weight: 4
    id: billing
    settings:
      default_same_address: false
  payment:
    status: true
    weight: 6
    id: payment
    settings:
      show_preview: true
  comments:
    status: true
    weight: 7
    id: comments
_core:
  default_config_hash: BkYk0dIIwOkaJMLizzK09J0HXWDcarGDOU520hzNoGY
